version: "3.5"

services:
  api01: &api01
    build: .
    hostname: api01
    command: python3 main.py --processes=4 --workers=2 --log-level=WARN
    environment:
      DATABASE_URL: postgresql://rinha:rinha@db/rinha?connect_timeout=60
      DATABASE_MAX_POOL_SIZE: 150
      ROBYN_PORT: 81
      ROBYN_HOST: 0.0.0.0
    network_mode: host
    depends_on:
      - db
    expose:
      - 81
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.5GB"

  api02:
    <<: *api01
    hostname: api02
    environment:
      DATABASE_URL: postgresql://rinha:rinha@localhost:5432/rinha?connect_timeout=60
      DATABASE_MAX_POOL_SIZE: 100
      ROBYN_PORT: 82
      ROBYN_HOST: 0.0.0.0
    expose:
      - 82

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: host
    expose:
      - 9999
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "0.7GB"

  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    network_mode: host
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    expose:
      - 5432
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "1.3GB"
